[package]
name = "bank-csv"
version = "0.1.0"
edition = "2021"
description = "Handle CSV files from a few German banks and PayPal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.18", features = ["derive"] }
csv = "1.3.0"
polars = {version = "0.36.2", features = ["csv", "lazy", "rows", "dtype-date"]}
sorted-vec = "0.8.3"
